document.addEventListener('DOMContentLoaded',()=>{
 const $=id=>document.getElementById(id); const state={token:localStorage.getItem('aguacate-token')||null,id:localStorage.getItem('aguacate-id')||'',role:'user',conversations:[],activeId:null,litres:0};
 const api=async(url,opt={})=>{opt.headers={...(opt.headers||{}),Authorization:`Bearer ${state.token}`};const r=await fetch(url,opt);let j={};try{j=await r.json()}catch{};if(!r.ok){if(j.error==='banned'){localStorage.removeItem('aguacate-token');openToast('⛔ Accès suspendu pendant 24 h.')}throw new Error(j.message||j.error||`HTTP ${r.status}`)}return j};
 const openToast=t=>{const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2800)};
 function ecoColor(p){if(p<=20)return '#45cf70';if(p<=50)return '#e7c84a';if(p<=85)return '#ee8f3d';return '#ef5555'}
 function renderEco(){const l=state.litres,p=Math.min(100,l),c=ecoColor(p);$('eco-litres').textContent=l.toFixed(1).replace('.',',')+' L';$('eco-detail-litres').textContent=l.toFixed(1).replace('.',',')+' L';$('eco-detail-pct').textContent=Math.round(p)+'%';$('eco-mini-fill').style.width=p+'%';$('eco-mini-fill').style.background=c;$('eco-vertical-fill').style.height=p+'%';$('eco-vertical-fill').style.background=c;$('eco-marker').style.bottom=p+'%';let s=p<=20?'🟢 Faible':p<=50?'🟡 Modéré':p<=85?'🟠 Élevé':'🔴 Très élevé';$('eco-status').textContent=s;$('eco-detail-status').textContent=s;$('eco-detail-status').style.color=c}
 function openPanel(id){const e=$(id);e.classList.remove('hidden');e.setAttribute('aria-hidden','false')};function closePanel(id){const e=$(id);e.classList.add('hidden');e.setAttribute('aria-hidden','true')}
 function drawer(open){$('drawer').classList.toggle('open',open);$('drawer-backdrop').classList.toggle('show',open);$('drawer').setAttribute('aria-hidden',String(!open))}
 function addMessage(role,text){const d=document.createElement('div');d.className='message '+(role==='user'?'user':'ai');d.textContent=text;$('messages').appendChild(d);$('messages').scrollTop=$('messages').scrollHeight;return d}
 function renderMessages(arr){$('messages').innerHTML='';$('hero').classList.toggle('hidden',arr.length>0);arr.forEach(m=>addMessage(m.role==='assistant'?'ai':'user',m.content||''))}
 function renderConversations(){const box=$('conversation-list');box.innerHTML='';state.conversations.forEach(c=>{const row=document.createElement('div');row.className='conversation-row'+(c.id===state.activeId?' active':'');const b=document.createElement('button');b.className='conversation-item';b.textContent=c.title||'Conversation';b.onclick=()=>{state.activeId=c.id;renderConversations();renderMessages(c.messages||[]);drawer(false)};const del=document.createElement('button');del.className='conversation-delete';del.textContent='🗑️';del.onclick=async e=>{e.stopPropagation();if(!confirm(`Supprimer « ${c.title||'Conversation'} » ?`))return;try{const j=await api('/deleteConversation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversationId:c.id})});state.conversations=j.conversations||[];state.activeId=state.conversations.at(-1)?.id||null;renderConversations();renderMessages(state.conversations.find(x=>x.id===state.activeId)?.messages||[])}catch(err){openToast(err.message)}};row.append(b,del);box.appendChild(row)})}
 async function login(){const r=await fetch('/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceId:state.id})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.message||j.error||'Connexion impossible');state.token=j.token;state.id=j.id;state.role=j.role||'user';state.litres=Number(j.consumptionLitres||0);localStorage.setItem('aguacate-token',j.token);localStorage.setItem('aguacate-id',j.id);$('user-badge').textContent='🥑 Aguacate AI #'+state.id;$('role-badge').textContent=state.role.toUpperCase();renderEco();await loadConversations()}
 async function loadConversations(){const j=await api('/conversations');state.conversations=j||[];state.activeId=state.activeId||state.conversations.at(-1)?.id||null;renderConversations();const c=state.conversations.find(x=>x.id===state.activeId);renderMessages(c?.messages||[])}
 async function send(text){const input=$('prompt'),msg=(text??input.value).trim();if(!msg)return;addMessage('user',msg);input.value='';input.style.height='auto';const wait=addMessage('ai','🥑 Aguacate réfléchit…');wait.classList.add('typing');try{const j=await api('/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:msg,mode:'Kids'})});wait.remove();addMessage('ai',j.reply||'');state.litres=Number(j.consumptionLitres||state.litres);renderEco();await loadConversations()}catch(e){wait.textContent='🥑 '+e.message;openToast(e.message)}}
 $('composer').onsubmit=e=>{e.preventDefault();send()};$('prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};$('prompt').oninput=e=>{e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,130)+'px'};document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>send(b.dataset.prompt));
 $('menu-btn').onclick=()=>drawer(true);$('close-drawer').onclick=()=>drawer(false);$('drawer-backdrop').onclick=()=>drawer(false);$('eco-open-btn').onclick=()=>{drawer(false);openPanel('eco-panel')};$('eco-top-btn').onclick=()=>openPanel('eco-panel');$('rules-btn').onclick=()=>{drawer(false);openPanel('rules-panel')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closePanel(b.dataset.close));
 $('theme-btn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('aguacate-theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('aguacate-theme')==='light')document.body.classList.add('light');
 $('new-chat-btn').onclick=async()=>{try{const j=await api('/newConversation',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});state.conversations=j.conversations;state.activeId=j.id;renderConversations();renderMessages([]);drawer(false)}catch(e){openToast(e.message)}};
 $('rename-btn').onclick=async()=>{if(!state.activeId)return openToast('Aucune conversation sélectionnée');const c=state.conversations.find(x=>x.id===state.activeId);const title=prompt('Nouveau nom :',c?.title||'');if(!title)return;try{await api('/renameConversation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversationId:state.activeId,title})});await loadConversations()}catch(e){openToast(e.message)}};
 $('attach-btn').onclick=()=>$('file-input').click();$('file-tool-btn').onclick=()=>{drawer(false);$('file-input').click()};$('file-input').onchange=async e=>{const f=e.target.files[0];if(!f)return;const fd=new FormData();fd.append('file',f);fd.append('question',$('prompt').value.trim()||'Résume ce fichier et donne-moi les informations importantes.');$('file-preview').classList.remove('hidden');$('file-preview').textContent='📄 '+f.name+' — analyse en cours…';try{const j=await api('/scan-and-ask',{method:'POST',body:fd});$('file-preview').textContent='📄 '+j.fileName+' — '+j.characters+' caractères extraits';addMessage('ai',j.reply||'');await loadConversations();state.litres=Number(j.consumptionLitres||state.litres);renderEco();openToast('Fichier analysé ✨')}catch(err){$('file-preview').textContent='❌ '+err.message;openToast(err.message)}e.target.value=''};
 $('mic-btn').onclick=()=>window.AguacateVoice?.toggle?.($('prompt'),openToast);
 $('admin-open-btn').onclick=()=>{drawer(false);window.AguacateAdmin?.open?.()};$('admin-refresh').onclick=()=>window.AguacateAdmin?.open?.(true);
 setInterval(()=>{if(state.token)api('/heartbeat').catch(()=>{})},30000);login().catch(e=>openToast('Connexion impossible : '+e.message));renderEco();
 window.AguacateApp={state,api,openToast,renderEco,openPanel,closePanel};
});
